CREATE DATABASE compras_api;

USE compras_api;

CREATE TABLE PEDIDOS ( 
	CD_PEDIDO MEDIUMINT NOT NULL AUTO_INCREMENT, 
	VR_PEDIDO FLOAT(10,7) NOT NULL, 
	CD_STATUS VARCHAR(1) NOT NULL, 
	DT_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	DT_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	PRIMARY KEY (CD_PEDIDO) 
	); 
	
INSERT INTO PEDIDOS ( 
	VR_PEDIDO, CD_STATUS 
	) 
	VALUES ( 
	'15.50', 
	'1' 
	); 
	
INSERT INTO PEDIDOS ( 
	VR_PEDIDO, CD_STATUS 
	) VALUES ( 
	'17.30', 
	'2' 
	); 
	
INSERT INTO PEDIDOS ( 
	VR_PEDIDO, CD_STATUS 
	) VALUES ( 
	'17.30', 
	'3' 
	); 
	
INSERT INTO PEDIDOS ( 
	VR_PEDIDO, CD_STATUS 
	) VALUES ( 
	'17.30', 
	'4' 
	); 
	
SELECT * FROM PEDIDOS ;